language: java
cache:
  directories:
    - $HOME/.m2
env:
  global:
  - DISPLAY=:99.0
services:
  - xvfb
before_install:
  - wget https://archive.apache.org/dist/maven/maven-3/3.6.0/binaries/apache-maven-3.6.0-bin.zip
  - unzip -qqo apache-maven-3.6.0-bin.zip
  - export M2_HOME=$PWD/apache-maven-3.6.0
  - export PATH=$M2_HOME/bin:$PATH
  # ----
  - sudo apt-get install apt-transport-https
  - sudo sh -c 'wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'
  - sudo sh -c 'wget -qO- https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list'
  - sudo apt-get update
  - sudo apt-get install dart
  - dart --version

install: true
script:
  - mvn test
